### ISSUE TITLE
ResourceExhausted - with very large RIB

### ISSUE THREAD

**Issue by Thoro** [osrg/gobgp#1430]
When accessing the RIB via gobgp with a full feed IPv4 routing table the cli utility breaks with:

```
rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (111528896 vs. 4194304)
```

I'm not sure if just increasing the message size is useful, or if you could pass something like offset and count for paging through.

**Comment by fujita** [comment]
https://github.com/dgraph-io/dgraph/issues/1073
grpc-go bug?

**Comment by Thoro** [comment]
I would believe there's some setting somewhere see: https://github.com/dgraph-io/dgraph/pull/1100/files

**Comment by fujita** [comment]
Oops, I've pushed a fix.

**Comment by fujita** [comment]
Pushed. Let me know if you still hit this.

**Comment by Thoro** [comment]
It's not completely fixed, the client side needs the same changes:

client/client.go and gobgp/cmd/common.go and add the option grpc.WithMaxMsgSize(256 << 20)
