### ISSUE TITLE
Big challenge with default export filters

### ISSUE THREAD

**Issue by pavel-odintsov** [osrg/gobgp#596]
Hello!

I'm using GoBGP as client for 2 BGP router servers. And I hit very_popular and ugly issue - I have reannounced all received prefixes from first uplink to the second and vice versa.

So fortunately I have filters on opposite side and I haven;t broken Internet. 

So I have multiple questions / suggestions. 

First of all, I want to ask to set default export policy to reject or just reject re-announce prefixes received from other uplink to another. 

If somebody want it it should _explicitly_ enable this.

I have achieved this with following CLI command:
```bash
gobgp global policy export set default reject    
```

But I haven't any idea how to do same with configuration file. Could you help me here?

**Comment by ishidawataru** [comment]
Hi, please try this

```toml
[global.config]
  as = 1
  router-id = "1.1.1.1"
  [global.apply-policy.config]
    default-export-policy = "reject-route"
```

**Comment by pavel-odintsov** [comment]
Works perfectly! Thanks you so much! What do you think about making this option default?

**Comment by pavel-odintsov** [comment]
Hello!

Looks like you have bug in code related with default-export-policy = "reject-route".

I have GoBGP instance with 2 neighbors and following configuration:
```bash
[global.config]
  as = xxx
  router-id = "xxx"

  [global.apply-policy.config]
    default-export-policy = "reject-route"
```

As you can see all outgoing routes should be rejected.

But for very strange reasons they haven't! :(

```bash
 gobgp neighbor
Peer               AS     Up/Down State       |#Advertised Received Accepted
xxxx    xxx 2d 22:50:40 Establ      |          0    33558    33558
yyyy    xxx 3d 02:50:55 Establ      |        247    33570    33570
```

As you can see for very-very-very strange reasons we announce 247 routes to the yyyy neighbor.

Please check this:
```bash
gobgp neighbor yyyy adj-out|wc -l 
247
```

I have checked all announced routes here. And they definitely received from another peer....

**Comment by pavel-odintsov** [comment]
We have experienced multiple restarts of neighbors:

```bash
{"level":"info","msg":"gobgpd started","time":"2016-01-18T16:25:17+03:00"}
{"level":"info","msg":"finished reading the config file","time":"2016-01-18T16:25:17+03:00"}
{"level":"info","msg":"Peer yyyyyy is added","time":"2016-01-18T16:25:17+03:00"}
{"level":"info","msg":"roa server is connected, 127.0.0.1:8383","time":"2016-01-18T16:25:17+03:00"}
{"level":"info","msg":"Peer xxxxx is added","time":"2016-01-18T16:25:17+03:00"}


{"Key":"yyyyy","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-01-18T16:25:18+03:00"}
{"Key":"xxxxxx","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-01-18T16:25:29+03:00"}
{"Key":"xxxx","Reason":"Peer closed the session","State":6,"Topic":"Peer","level":"info","msg":"Peer Down","time":"2016-01-19T09:18:09+03:00"}
{"Key":"xxxxx","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-01-19T09:28:08+03:00"}
{"Key":"yyyy","Reason":"Peer closed the session","State":6,"Topic":"Peer","level":"info","msg":"Peer Down","time":"2016-01-19T12:45:55+03:00"}
{"Key":"yyyy","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-01-19T12:46:58+03:00"}
{"Key":"yyyy","Reason":"Peer closed the session","State":6,"Topic":"Peer","level":"info","msg":"Peer Down","time":"2016-01-26T12:45:22+03:00"}
{"Key":"yyyy","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-01-26T12:45:44+03:00"}
{"Key":"xxxx","Reason":"Peer closed the session","State":6,"Topic":"Peer","level":"info","msg":"Peer Down","time":"2016-01-26T16:45:29+03:00"}
{"Key":"xxxx","State":5,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-01-26T16:45:59+03:00"}

```

**Comment by ishidawataru** [comment]
Are these restarts are intentional?

**Comment by pavel-odintsov** [comment]
Yep, it's planned route server restarts.

**Comment by ishidawataru** [comment]
OK, and the peers of gobgp are not configured as a router-server client, right?

**Comment by pavel-odintsov** [comment]
After fresh GOBGP restart everything working fine:
```bash
gobgp nei
Peer               AS  Up/Down State       |#Advertised Received Accepted
xxxx    xx 00:03:13 Establ      |          0    33558    33558
yyyy    xx 00:03:14 Establ      |          0    33570    33570
```

With zero announced routes as requested.

**Comment by pavel-odintsov** [comment]
They are configured as standard BGP clients (not route-server client's).

**Comment by ishidawataru** [comment]
I see. One more question.
Routes which were accidentally advertised to peer yyyy is advertised from peer xxxx at the same time?
You can see that from the timestamp of adj-in view.

**Comment by pavel-odintsov** [comment]
Unfortunately, I lost this information when restart GoBGP :(

**Comment by ishidawataru** [comment]
Ok, thanks. I will try to reproduce the problem.

**Comment by pavel-odintsov** [comment]
I have reproduced it!

Just run it:
```bash
gobgp neighbor 
Peer               AS  Up/Down State       |#Advertised Received Accepted
xxx    xx 00:00:14 Establ      |          0    33560    33560
yyy    xx 00:00:14 Establ      |          0    33572    33572

```

Then call resytart for one peer:
```bash
gobgp neighbor xxxx reset
```

And got this announces:
```bash
gobgp neighbor 
Peer               AS  Up/Down State       |#Advertised Received Accepted
xxxxxx    x 00:00:04 Idle        |          0        0        0
yyy    xx 00:00:31 Establ      |        146    33570    33570
```

As you can see broken routes arrives when we doing peer restart.

**Comment by ishidawataru** [comment]
Thanks a lot! Also reproduced here. Will fix it soon.

**Comment by pavel-odintsov** [comment]
That's nice!

**Comment by ishidawataru** [comment]
Fixed by this #650 

Could you check?

**Comment by pavel-odintsov** [comment]
Hello!

Thanks! Working fine. 

But I'm still getting some strange messages in log:
```bash
{"Key":"xxx","State":4,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-02-01T10:12:43+03:00"}
{"Key":"yyy","State":4,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-02-01T10:12:43+03:00"}
{"Key":"xxxx","Topic":"Operation","level":"info","msg":"Neighbor reset","time":"2016-02-01T10:20:48+03:00"}
{"Data":{"Header":{"Marker":null,"Len":21,"Type":3},"Body":{"ErrorCode":6,"ErrorSubcode":4,"Data":null}},"Key":"keepitsecret","State":5,"Topic":"Peer","level":"warning","msg":"sent notification","time":"2016-02-01T10:20:48+03:00"}
{"Key":"xxxxx","Reason":5,"State":5,"Topic":"Peer","level":"info","msg":"Peer Down","time":"2016-02-01T10:20:48+03:00"}



{"Key":"194.226.71.55","Topic":"Peer","level":"warning","msg":"Closed an accepted connection","time":"2016-02-01T10:20:57+03:00"}
{"Key":"194.226.71.55","Topic":"Peer","level":"warning","msg":"Closed an accepted connection","time":"2016-02-01T10:21:01+03:00"}
{"Key":"194.226.71.55","Topic":"Peer","level":"warning","msg":"Closed an accepted connection","time":"2016-02-01T10:21:06+03:00"}
{"Key":"194.226.71.55","Topic":"Peer","level":"warning","msg":"Closed an accepted connection","time":"2016-02-01T10:21:10+03:00"}
{"Key":"194.226.71.55","Topic":"Peer","level":"warning","msg":"Closed an accepted connection","time":"2016-02-01T10:21:14+03:00"}
{"Key":"194.226.71.55","State":4,"Topic":"Peer","level":"info","msg":"Peer Up","time":"2016-02-01T10:21:19+03:00"}
```

**Comment by pavel-odintsov** [comment]
Just small request... What about moving "time" to first field of debug output instead "key"?

**Comment by ishidawataru** [comment]
Thanks for checking!

The behavior is not wrong. But it would be better to change the log level to `debug` from `warning`.
After reset, `gobgpd` waits 30s by default for a new tcp connection. New connection from the peer during this hold-time will be closed. The value of hold-time can be changed by setting `neighbor.timers.config.idle-hold-time-after-reset`.

**Comment by pavel-odintsov** [comment]
OK, nice! Thanks! Thus closing issue!
